CONNECT '/var/lib/firebird/data/indicadores_gt.fdb';
/* ==========================
   UBICACIONES
   ========================== */
CREATE TABLE departamento (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    codigo VARCHAR(10) NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    CONSTRAINT pk_departamento PRIMARY KEY (id),
    CONSTRAINT uq_departamento_codigo UNIQUE (codigo)
);

CREATE TABLE municipio (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    codigo VARCHAR(10) NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    id_departamento INTEGER NOT NULL,
    CONSTRAINT pk_municipio PRIMARY KEY (id),
    CONSTRAINT uq_municipio_dep_codigo UNIQUE (id_departamento, codigo),
    CONSTRAINT fk_municipio_departamento FOREIGN KEY (id_departamento) REFERENCES departamento (id)
);

CREATE TABLE area_geografica (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(50) NOT NULL,
    CONSTRAINT pk_area_geografica PRIMARY KEY (id),
    CONSTRAINT uq_area_geografica_nombre UNIQUE (nombre)
);

/* ==========================
   TEMPORALIDAD
   ========================== */
CREATE TABLE franja_horaria (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    codigo VARCHAR(10) NOT NULL,
    nombre VARCHAR(50) NOT NULL,
    hora_inicio TIME NOT NULL,
    hora_fin TIME NOT NULL,
    CONSTRAINT pk_franja_horaria PRIMARY KEY (id),
    CONSTRAINT uq_franja_horaria_codigo UNIQUE (codigo),
    CONSTRAINT ck_franja_horaria_rango CHECK (hora_inicio <= hora_fin)
);

CREATE TABLE fecha (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    fecha DATE NOT NULL,
    anio SMALLINT NOT NULL,
    mes SMALLINT NOT NULL,
    nombre_mes VARCHAR(20) NOT NULL,
    dia SMALLINT NOT NULL,
    dia_semana VARCHAR(20) NOT NULL,
    CONSTRAINT pk_fecha PRIMARY KEY (id),
    CONSTRAINT uq_fecha_fecha UNIQUE (fecha),
    CONSTRAINT ck_fecha_mes CHECK (mes BETWEEN 1 AND 12),
    CONSTRAINT ck_fecha_dia CHECK (dia BETWEEN 1 AND 31)
);

/* ==========================
   CATALOGO / DICCIONARIO
   ========================== */
CREATE TABLE sexo (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    codigo VARCHAR(10) NOT NULL,
    nombre VARCHAR(30) NOT NULL,
    CONSTRAINT pk_sexo PRIMARY KEY (id),
    CONSTRAINT uq_sexo_codigo UNIQUE (codigo)
);

CREATE TABLE zona (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    codigo VARCHAR(10) NOT NULL,
    descripcion VARCHAR(100) NOT NULL,
    CONSTRAINT pk_zona PRIMARY KEY (id),
    CONSTRAINT uq_zona_codigo UNIQUE (codigo)
);

CREATE TABLE estado_conyugal (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    codigo VARCHAR(10) NOT NULL,
    nombre VARCHAR(50) NOT NULL,
    CONSTRAINT pk_estado_conyugal PRIMARY KEY (id),
    CONSTRAINT uq_estado_conyugal_codigo UNIQUE (codigo)
);

CREATE TABLE grupo_etario (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    codigo VARCHAR(20) NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    edad_min SMALLINT,
    edad_max SMALLINT,
    tipo_grupo VARCHAR(50),
    CONSTRAINT pk_grupo_etario PRIMARY KEY (id),
    CONSTRAINT uq_grupo_etario_codigo UNIQUE (codigo),
    CONSTRAINT ck_grupo_etario_rango CHECK (
        (edad_min IS NULL AND edad_max IS NULL) OR (edad_min IS NOT NULL AND edad_max IS NOT NULL AND edad_min <= edad_max)
    )
);

CREATE TABLE categoria_delito (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    codigo VARCHAR(20) NOT NULL,
    nombre VARCHAR(150) NOT NULL,
    CONSTRAINT pk_categoria_delito PRIMARY KEY (id),
    CONSTRAINT uq_categoria_delito_codigo UNIQUE (codigo)
);

CREATE TABLE tipo_fallo (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    codigo VARCHAR(20) NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    CONSTRAINT pk_tipo_fallo PRIMARY KEY (id),
    CONSTRAINT uq_tipo_fallo_codigo UNIQUE (codigo)
);

CREATE TABLE fuente_dato (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    institucion VARCHAR(150) NOT NULL,
    dataset VARCHAR(200) NOT NULL,
    tipo_fuente VARCHAR(50) NOT NULL,
    CONSTRAINT pk_fuente_dato PRIMARY KEY (id)
);

CREATE TABLE involucramiento (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    codigo VARCHAR(20) NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    CONSTRAINT pk_involucramiento PRIMARY KEY (id),
    CONSTRAINT uq_involucramiento_codigo UNIQUE (codigo)
);

CREATE TABLE tipo_ley (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    codigo VARCHAR(20) NOT NULL,
    nombre VARCHAR(150) NOT NULL,
    CONSTRAINT pk_tipo_ley PRIMARY KEY (id),
    CONSTRAINT uq_tipo_ley_codigo UNIQUE (codigo)
);

CREATE TABLE titulo_ley (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    codigo VARCHAR(20) NOT NULL,
    nombre VARCHAR(150) NOT NULL,
    id_tipo_ley INTEGER NOT NULL,
    CONSTRAINT pk_titulo_ley PRIMARY KEY (id),
    CONSTRAINT uq_titulo_ley_codigo UNIQUE (codigo),
    CONSTRAINT fk_titulo_ley_tipo_ley FOREIGN KEY (id_tipo_ley) REFERENCES tipo_ley (id)
);

CREATE TABLE capitulo_ley (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    codigo VARCHAR(20) NOT NULL,
    nombre VARCHAR(150) NOT NULL,
    id_titulo INTEGER NOT NULL,
    CONSTRAINT pk_capitulo_ley PRIMARY KEY (id),
    CONSTRAINT uq_capitulo_ley_codigo UNIQUE (codigo),
    CONSTRAINT fk_capitulo_ley_titulo FOREIGN KEY (id_titulo) REFERENCES titulo_ley (id)
);

CREATE TABLE delito (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    codigo VARCHAR(20) NOT NULL,
    nombre VARCHAR(200) NOT NULL,
    id_capitulo INTEGER,
    id_categoria_delito INTEGER,
    CONSTRAINT pk_delito PRIMARY KEY (id),
    CONSTRAINT uq_delito_codigo UNIQUE (codigo),
    CONSTRAINT fk_delito_capitulo FOREIGN KEY (id_capitulo) REFERENCES capitulo_ley (id),
    CONSTRAINT fk_delito_categoria FOREIGN KEY (id_categoria_delito) REFERENCES categoria_delito (id)
);

CREATE TABLE nacionalidad (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    codigo VARCHAR(20) NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    CONSTRAINT pk_nacionalidad PRIMARY KEY (id),
    CONSTRAINT uq_nacionalidad_codigo UNIQUE (codigo)
);

CREATE TABLE condicion_edad (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    codigo VARCHAR(20) NOT NULL,
    nombre VARCHAR(50) NOT NULL,
    CONSTRAINT pk_condicion_edad PRIMARY KEY (id),
    CONSTRAINT uq_condicion_edad_codigo UNIQUE (codigo)
);

CREATE TABLE causa_muerte (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    codigo VARCHAR(20) NOT NULL,
    nombre VARCHAR(150) NOT NULL,
    CONSTRAINT pk_causa_muerte PRIMARY KEY (id),
    CONSTRAINT uq_causa_muerte_codigo UNIQUE (codigo)
);

CREATE TABLE clasificacion_evaluacion (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    codigo VARCHAR(20) NOT NULL,
    nombre VARCHAR(200) NOT NULL,
    CONSTRAINT pk_clasificacion_evaluacion PRIMARY KEY (id),
    CONSTRAINT uq_clasificacion_eval_codigo UNIQUE (codigo)
);

CREATE TABLE estado_caso (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    codigo VARCHAR(20) NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    CONSTRAINT pk_estado_caso PRIMARY KEY (id),
    CONSTRAINT uq_estado_caso_codigo UNIQUE (codigo)
);

CREATE TABLE escolaridad (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(100) NOT NULL,
    CONSTRAINT pk_escolaridad PRIMARY KEY (id),
    CONSTRAINT uq_escolaridad_nombre UNIQUE (nombre)
);

CREATE TABLE grupo_etnico (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(100) NOT NULL,
    CONSTRAINT pk_grupo_etnico PRIMARY KEY (id),
    CONSTRAINT uq_grupo_etnico_nombre UNIQUE (nombre)
);

CREATE TABLE orientacion (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(100) NOT NULL,
    CONSTRAINT pk_orientacion PRIMARY KEY (id),
    CONSTRAINT uq_orientacion_nombre UNIQUE (nombre)
);

CREATE TABLE tipo_denuncia (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(100) NOT NULL,
    CONSTRAINT pk_tipo_denuncia PRIMARY KEY (id),
    CONSTRAINT uq_tipo_denuncia_nombre UNIQUE (nombre)
);

CREATE TABLE tipo_hecho_delictivo (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(200) NOT NULL,
    CONSTRAINT pk_tipo_hecho_delictivo PRIMARY KEY (id),
    CONSTRAINT uq_tipo_hecho_delictivo_nombre UNIQUE (nombre)
);

CREATE TABLE sede (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(150) NOT NULL,
    id_municipio INTEGER NOT NULL,
    CONSTRAINT pk_sede PRIMARY KEY (id),
    CONSTRAINT fk_sede_municipio FOREIGN KEY (id_municipio) REFERENCES municipio (id)
);

CREATE TABLE tipo_atencion (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(100) NOT NULL,
    CONSTRAINT pk_tipo_atencion PRIMARY KEY (id),
    CONSTRAINT uq_tipo_atencion_nombre UNIQUE (nombre)
);

CREATE TABLE tipo_delito_atendido (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(200) NOT NULL,
    CONSTRAINT pk_tipo_delito_atendido PRIMARY KEY (id),
    CONSTRAINT uq_tipo_delito_atendido_nombre UNIQUE (nombre)
);

CREATE TABLE despacho_judicial (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(200) NOT NULL,
    CONSTRAINT pk_despacho_judicial PRIMARY KEY (id),
    CONSTRAINT uq_despacho_judicial_nombre UNIQUE (nombre)
);

CREATE TABLE sector_economico (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(100) NOT NULL,
    CONSTRAINT pk_sector_economico PRIMARY KEY (id),
    CONSTRAINT uq_sector_economico_nombre UNIQUE (nombre)
);

CREATE TABLE condicion_actividad (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(100) NOT NULL,
    CONSTRAINT pk_condicion_actividad PRIMARY KEY (id),
    CONSTRAINT uq_condicion_actividad_nombre UNIQUE (nombre)
);

CREATE TABLE motivo_trabajo (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(150) NOT NULL,
    CONSTRAINT pk_motivo_trabajo PRIMARY KEY (id),
    CONSTRAINT uq_motivo_trabajo_nombre UNIQUE (nombre)
);

CREATE TABLE apoyo_hogar (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(100) NOT NULL,
    CONSTRAINT pk_apoyo_hogar PRIMARY KEY (id),
    CONSTRAINT uq_apoyo_hogar_nombre UNIQUE (nombre)
);

CREATE TABLE tipo_trabajo (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(100) NOT NULL,
    CONSTRAINT pk_tipo_trabajo PRIMARY KEY (id),
    CONSTRAINT uq_tipo_trabajo_nombre UNIQUE (nombre)
);

CREATE TABLE tipo_agresion (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(150) NOT NULL,
    CONSTRAINT pk_tipo_agresion PRIMARY KEY (id),
    CONSTRAINT uq_tipo_agresion_nombre UNIQUE (nombre)
);

CREATE TABLE tipo_medida (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    codigo VARCHAR(20) NOT NULL,
    nombre VARCHAR(150) NOT NULL,
    CONSTRAINT pk_tipo_medida PRIMARY KEY (id),
    CONSTRAINT uq_tipo_medida_codigo UNIQUE (codigo)
);

CREATE TABLE relacion_agresor (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    codigo VARCHAR(20) NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    CONSTRAINT pk_relacion_agresor PRIMARY KEY (id),
    CONSTRAINT uq_relacion_agresor_codigo UNIQUE (codigo)
);

CREATE TABLE tipo_falta (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    codigo VARCHAR(20) NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    CONSTRAINT pk_tipo_falta PRIMARY KEY (id),
    CONSTRAINT uq_tipo_falta_codigo UNIQUE (codigo)
);

CREATE TABLE condicion_alfabetismo (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    codigo VARCHAR(20) NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    CONSTRAINT pk_condicion_alfabetismo PRIMARY KEY (id),
    CONSTRAINT uq_condicion_alfabetismo_codigo UNIQUE (codigo)
);

CREATE TABLE estado_ebriedad (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    codigo VARCHAR(20) NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    CONSTRAINT pk_estado_ebriedad PRIMARY KEY (id),
    CONSTRAINT uq_estado_ebriedad_codigo UNIQUE (codigo)
);

CREATE TABLE ocupacion (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    codigo VARCHAR(20) NOT NULL,
    nombre VARCHAR(150) NOT NULL,
    CONSTRAINT pk_ocupacion PRIMARY KEY (id),
    CONSTRAINT uq_ocupacion_codigo UNIQUE (codigo)
);

CREATE TABLE tipo_discriminacion (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(150) NOT NULL,
    CONSTRAINT pk_tipo_discriminacion PRIMARY KEY (id),
    CONSTRAINT uq_tipo_discriminacion_nombre UNIQUE (nombre)
);

CREATE TABLE comunidad_linguistica (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(150) NOT NULL,
    CONSTRAINT pk_comunidad_linguistica PRIMARY KEY (id),
    CONSTRAINT uq_comunidad_linguistica_nombre UNIQUE (nombre)
);

CREATE TABLE diagnostico_cie10 (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    codigo VARCHAR(20) NOT NULL,
    nombre VARCHAR(400) NOT NULL,
    CONSTRAINT pk_diagnostico_cie10 PRIMARY KEY (id),
    CONSTRAINT uq_diagnostico_cie10_codigo UNIQUE (codigo)
);

CREATE TABLE tipo_indicador_salud (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(150) NOT NULL,
    CONSTRAINT pk_tipo_indicador_salud PRIMARY KEY (id),
    CONSTRAINT uq_tipo_indicador_salud_nombre UNIQUE (nombre)
);

CREATE TABLE enfermedad (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(300) NOT NULL,
    tipo VARCHAR(100),
    CONSTRAINT pk_enfermedad PRIMARY KEY (id)
);

/* ==========================
   PERSONAS
   ========================== */
CREATE TABLE persona (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_sexo INTEGER NOT NULL,
    edad SMALLINT,
    CONSTRAINT pk_persona PRIMARY KEY (id),
    CONSTRAINT fk_persona_sexo FOREIGN KEY (id_sexo) REFERENCES sexo (id),
    CONSTRAINT ck_persona_edad CHECK (edad IS NULL OR edad >= 0)
);

CREATE TABLE detalle_persona (
    id_persona INTEGER NOT NULL,
    id_estado_conyugal INTEGER,
    id_nacionalidad INTEGER,
    id_condicion_edad INTEGER,
    id_escolaridad INTEGER,
    id_grupo_etnico INTEGER,
    id_orientacion INTEGER,
    CONSTRAINT pk_detalle_persona PRIMARY KEY (id_persona),
    CONSTRAINT fk_detalle_persona_persona FOREIGN KEY (id_persona) REFERENCES persona (id),
    CONSTRAINT fk_detalle_persona_estado_conyugal FOREIGN KEY (id_estado_conyugal) REFERENCES estado_conyugal (id),
    CONSTRAINT fk_detalle_persona_nacionalidad FOREIGN KEY (id_nacionalidad) REFERENCES nacionalidad (id),
    CONSTRAINT fk_detalle_persona_condicion_edad FOREIGN KEY (id_condicion_edad) REFERENCES condicion_edad (id),
    CONSTRAINT fk_detalle_persona_escolaridad FOREIGN KEY (id_escolaridad) REFERENCES escolaridad (id),
    CONSTRAINT fk_detalle_persona_grupo_etnico FOREIGN KEY (id_grupo_etnico) REFERENCES grupo_etnico (id),
    CONSTRAINT fk_detalle_persona_orientacion FOREIGN KEY (id_orientacion) REFERENCES orientacion (id)
);

/* ==========================
   DENUNCIAS / HECHOS
   ========================== */
CREATE TABLE hecho_delictivo (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_fecha INTEGER NOT NULL,
    id_municipio INTEGER NOT NULL,
    id_zona INTEGER,
    id_delito INTEGER NOT NULL,
    id_area_geografica INTEGER,
    id_franja_horaria INTEGER,
    CONSTRAINT pk_hecho_delictivo PRIMARY KEY (id),
    CONSTRAINT fk_hecho_delictivo_fecha FOREIGN KEY (id_fecha) REFERENCES fecha (id),
    CONSTRAINT fk_hecho_delictivo_municipio FOREIGN KEY (id_municipio) REFERENCES municipio (id),
    CONSTRAINT fk_hecho_delictivo_zona FOREIGN KEY (id_zona) REFERENCES zona (id),
    CONSTRAINT fk_hecho_delictivo_delito FOREIGN KEY (id_delito) REFERENCES delito (id),
    CONSTRAINT fk_hecho_delictivo_area FOREIGN KEY (id_area_geografica) REFERENCES area_geografica (id),
    CONSTRAINT fk_hecho_delictivo_franja FOREIGN KEY (id_franja_horaria) REFERENCES franja_horaria (id)
);

CREATE TABLE hecho_delictivo_mujer_estadistica (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_departamento INTEGER NOT NULL,
    id_fecha INTEGER NOT NULL,
    id_tipo_hecho_delictivo INTEGER NOT NULL,
    id_delito INTEGER,
    id_estado_caso INTEGER,
    cantidad INTEGER NOT NULL,
    CONSTRAINT pk_hd_mujer_estadistica PRIMARY KEY (id),
    CONSTRAINT fk_hd_mujer_est_dep FOREIGN KEY (id_departamento) REFERENCES departamento (id),
    CONSTRAINT fk_hd_mujer_est_fecha FOREIGN KEY (id_fecha) REFERENCES fecha (id),
    CONSTRAINT fk_hd_mujer_est_tipo FOREIGN KEY (id_tipo_hecho_delictivo) REFERENCES tipo_hecho_delictivo (id),
    CONSTRAINT fk_hd_mujer_est_delito FOREIGN KEY (id_delito) REFERENCES delito (id),
    CONSTRAINT fk_hd_mujer_est_estado_caso FOREIGN KEY (id_estado_caso) REFERENCES estado_caso (id),
    CONSTRAINT ck_hd_mujer_est_cantidad CHECK (cantidad >= 0)
);

CREATE TABLE delito_contra_vida_mujer_estadistica (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_municipio INTEGER NOT NULL,
    id_departamento INTEGER NOT NULL,
    id_fecha INTEGER NOT NULL,
    id_delito INTEGER NOT NULL,
    id_estado_caso INTEGER,
    cantidad INTEGER NOT NULL,
    CONSTRAINT pk_delito_vida_mujer_est PRIMARY KEY (id),
    CONSTRAINT fk_delito_vida_mujer_mun FOREIGN KEY (id_municipio) REFERENCES municipio (id),
    CONSTRAINT fk_delito_vida_mujer_dep FOREIGN KEY (id_departamento) REFERENCES departamento (id),
    CONSTRAINT fk_delito_vida_mujer_fecha FOREIGN KEY (id_fecha) REFERENCES fecha (id),
    CONSTRAINT fk_delito_vida_mujer_delito FOREIGN KEY (id_delito) REFERENCES delito (id),
    CONSTRAINT fk_delito_vida_mujer_estado FOREIGN KEY (id_estado_caso) REFERENCES estado_caso (id),
    CONSTRAINT ck_delito_vida_mujer_cantidad CHECK (cantidad >= 0)
);

CREATE TABLE denuncia (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_fecha INTEGER NOT NULL,
    id_hecho_delictivo INTEGER NOT NULL,
    id_persona INTEGER NOT NULL,
    id_estado_caso INTEGER,
    id_tipo_denuncia INTEGER,
    CONSTRAINT pk_denuncia PRIMARY KEY (id),
    CONSTRAINT fk_denuncia_fecha FOREIGN KEY (id_fecha) REFERENCES fecha (id),
    CONSTRAINT fk_denuncia_hecho FOREIGN KEY (id_hecho_delictivo) REFERENCES hecho_delictivo (id),
    CONSTRAINT fk_denuncia_persona FOREIGN KEY (id_persona) REFERENCES persona (id),
    CONSTRAINT fk_denuncia_estado FOREIGN KEY (id_estado_caso) REFERENCES estado_caso (id),
    CONSTRAINT fk_denuncia_tipo FOREIGN KEY (id_tipo_denuncia) REFERENCES tipo_denuncia (id)
);

CREATE TABLE involucramiento_hecho (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_persona INTEGER NOT NULL,
    id_hecho_delictivo INTEGER NOT NULL,
    id_involucramiento INTEGER NOT NULL,
    id_grupo_etario INTEGER,
    id_fuente_dato INTEGER,
    CONSTRAINT pk_involucramiento_hecho PRIMARY KEY (id),
    CONSTRAINT fk_involucramiento_hecho_persona FOREIGN KEY (id_persona) REFERENCES persona (id),
    CONSTRAINT fk_involucramiento_hecho_hecho FOREIGN KEY (id_hecho_delictivo) REFERENCES hecho_delictivo (id),
    CONSTRAINT fk_involucramiento_hecho_tipo FOREIGN KEY (id_involucramiento) REFERENCES involucramiento (id),
    CONSTRAINT fk_involucramiento_hecho_grupo FOREIGN KEY (id_grupo_etario) REFERENCES grupo_etario (id),
    CONSTRAINT fk_involucramiento_hecho_fuente FOREIGN KEY (id_fuente_dato) REFERENCES fuente_dato (id)
);

CREATE TABLE proceso_judicial (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_hecho_delictivo INTEGER NOT NULL,
    id_departamento INTEGER NOT NULL,
    id_delito INTEGER NOT NULL,
    CONSTRAINT pk_proceso_judicial PRIMARY KEY (id),
    CONSTRAINT fk_proceso_judicial_hecho FOREIGN KEY (id_hecho_delictivo) REFERENCES hecho_delictivo (id),
    CONSTRAINT fk_proceso_judicial_departamento FOREIGN KEY (id_departamento) REFERENCES departamento (id),
    CONSTRAINT fk_proceso_judicial_delito FOREIGN KEY (id_delito) REFERENCES delito (id)
);

CREATE TABLE sentencia (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_proceso_judicial INTEGER NOT NULL,
    id_tipo_fallo INTEGER NOT NULL,
    CONSTRAINT pk_sentencia PRIMARY KEY (id),
    CONSTRAINT fk_sentencia_proceso FOREIGN KEY (id_proceso_judicial) REFERENCES proceso_judicial (id),
    CONSTRAINT fk_sentencia_tipo_fallo FOREIGN KEY (id_tipo_fallo)  REFERENCES tipo_fallo (id)
);

CREATE TABLE medida_seguridad (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_proceso_judicial INTEGER NOT NULL,
    id_tipo_medida INTEGER NOT NULL,
    CONSTRAINT pk_medida_seguridad PRIMARY KEY (id),
    CONSTRAINT fk_medida_seguridad_proceso FOREIGN KEY (id_proceso_judicial) REFERENCES proceso_judicial (id),
    CONSTRAINT fk_medida_seguridad_tipo FOREIGN KEY (id_tipo_medida) REFERENCES tipo_medida (id)
);

CREATE TABLE medidas_seguridad_estadistica (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_municipio INTEGER NOT NULL,
    id_despacho INTEGER NOT NULL,
    id_fecha INTEGER NOT NULL,
    cantidad INTEGER NOT NULL,
    CONSTRAINT pk_medidas_seg_estadistica PRIMARY KEY (id),
    CONSTRAINT fk_medidas_seg_est_municipio FOREIGN KEY (id_municipio) REFERENCES municipio (id),
    CONSTRAINT fk_medidas_seg_est_despacho FOREIGN KEY (id_despacho) REFERENCES despacho_judicial (id),
    CONSTRAINT fk_medidas_seg_est_fecha FOREIGN KEY (id_fecha) REFERENCES fecha (id),
    CONSTRAINT ck_medidas_seg_est_cantidad CHECK (cantidad >= 0)
);

CREATE TABLE queja_mineduc_estadistica (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_departamento INTEGER NOT NULL,
    id_fecha INTEGER NOT NULL,
    id_tipo_agresion INTEGER NOT NULL,
    cantidad INTEGER NOT NULL,
    id_fuente_dato INTEGER,
    CONSTRAINT pk_queja_mineduc_estadistica PRIMARY KEY (id),
    CONSTRAINT fk_queja_mineduc_dep FOREIGN KEY (id_departamento) REFERENCES departamento (id),
    CONSTRAINT fk_queja_mineduc_fecha FOREIGN KEY (id_fecha) REFERENCES fecha (id),
    CONSTRAINT fk_queja_mineduc_tipo_agresion FOREIGN KEY (id_tipo_agresion) REFERENCES tipo_agresion (id),
    CONSTRAINT fk_queja_mineduc_fuente FOREIGN KEY (id_fuente_dato) REFERENCES fuente_dato (id),
    CONSTRAINT ck_queja_mineduc_cantidad CHECK (cantidad >= 0)
);

CREATE TABLE violencia_intrafamiliar (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_persona_victima INTEGER NOT NULL,
    id_persona_agresor INTEGER NOT NULL,
    id_hecho_delictivo INTEGER NOT NULL,
    id_relacion_agresor INTEGER,
    reiteracion_denuncia BOOLEAN,
    id_fuente_dato_denuncia_previa INTEGER,
    id_fuente_dato INTEGER,
    CONSTRAINT pk_violencia_intrafamiliar PRIMARY KEY (id),
    CONSTRAINT fk_vif_victima FOREIGN KEY (id_persona_victima) REFERENCES persona (id),
    CONSTRAINT fk_vif_agresor FOREIGN KEY (id_persona_agresor) REFERENCES persona (id),
    CONSTRAINT fk_vif_hecho FOREIGN KEY (id_hecho_delictivo) REFERENCES hecho_delictivo (id),
    CONSTRAINT fk_vif_relacion FOREIGN KEY (id_relacion_agresor) REFERENCES relacion_agresor (id),
    CONSTRAINT fk_vif_fuente_previa FOREIGN KEY (id_fuente_dato_denuncia_previa) REFERENCES fuente_dato (id),
    CONSTRAINT fk_vif_fuente FOREIGN KEY (id_fuente_dato) REFERENCES fuente_dato (id),
    CONSTRAINT ck_vif_personas_distintas CHECK (id_persona_victima <> id_persona_agresor)
);

CREATE TABLE falta_judicial (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_fecha INTEGER NOT NULL,
    id_municipio INTEGER NOT NULL,
    id_tipo_falta INTEGER NOT NULL,
    id_persona INTEGER NOT NULL,
    id_grupo_etario INTEGER,
    id_grupo_etnico INTEGER,
    id_condicion_alfabetismo INTEGER,
    id_escolaridad INTEGER,
    id_area_geografica INTEGER,
    id_estado_ebriedad INTEGER,
    id_ocupacion INTEGER,
    id_fuente_dato INTEGER,
    CONSTRAINT pk_falta_judicial PRIMARY KEY (id),
    CONSTRAINT fk_falta_judicial_fecha FOREIGN KEY (id_fecha) REFERENCES fecha (id),
    CONSTRAINT fk_falta_judicial_municipio FOREIGN KEY (id_municipio) REFERENCES municipio (id),
    CONSTRAINT fk_falta_judicial_tipo FOREIGN KEY (id_tipo_falta) REFERENCES tipo_falta (id),
    CONSTRAINT fk_falta_judicial_persona FOREIGN KEY (id_persona) REFERENCES persona (id),
    CONSTRAINT fk_falta_judicial_grupo_etario FOREIGN KEY (id_grupo_etario) REFERENCES grupo_etario (id),
    CONSTRAINT fk_falta_judicial_grupo_etnico FOREIGN KEY (id_grupo_etnico) REFERENCES grupo_etnico (id),
    CONSTRAINT fk_falta_judicial_cond_alf FOREIGN KEY (id_condicion_alfabetismo) REFERENCES condicion_alfabetismo (id),
    CONSTRAINT fk_falta_judicial_escolaridad FOREIGN KEY (id_escolaridad) REFERENCES escolaridad (id),
    CONSTRAINT fk_falta_judicial_area FOREIGN KEY (id_area_geografica) REFERENCES area_geografica (id),
    CONSTRAINT fk_falta_judicial_ebriedad FOREIGN KEY (id_estado_ebriedad) REFERENCES estado_ebriedad (id),
    CONSTRAINT fk_falta_judicial_ocupacion FOREIGN KEY (id_ocupacion) REFERENCES ocupacion (id),
    CONSTRAINT fk_falta_judicial_fuente FOREIGN KEY (id_fuente_dato) REFERENCES fuente_dato (id)
);

CREATE TABLE caso_discriminacion (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_fecha_aproximada INTEGER NOT NULL,
    id_persona INTEGER NOT NULL,
    id_departamento INTEGER NOT NULL,
    id_tipo_discriminacion INTEGER NOT NULL,
    id_grupo_etnico INTEGER,
    id_comunidad_linguistica INTEGER,
    id_fuente_dato INTEGER,
    CONSTRAINT pk_caso_discriminacion PRIMARY KEY (id),
    CONSTRAINT fk_caso_disc_fecha FOREIGN KEY (id_fecha_aproximada) REFERENCES fecha (id),
    CONSTRAINT fk_caso_disc_persona FOREIGN KEY (id_persona) REFERENCES persona (id),
    CONSTRAINT fk_caso_disc_departamento FOREIGN KEY (id_departamento) REFERENCES departamento (id),
    CONSTRAINT fk_caso_disc_tipo FOREIGN KEY (id_tipo_discriminacion) REFERENCES tipo_discriminacion (id),
    CONSTRAINT fk_caso_disc_grupo_etnico FOREIGN KEY (id_grupo_etnico) REFERENCES grupo_etnico (id),
    CONSTRAINT fk_caso_disc_comunidad FOREIGN KEY (id_comunidad_linguistica) REFERENCES comunidad_linguistica (id),
    CONSTRAINT fk_caso_disc_fuente FOREIGN KEY (id_fuente_dato) REFERENCES fuente_dato (id)
);

/* ==========================
   PROCESOS
   ========================== */
CREATE TABLE exhumacion (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_fecha INTEGER NOT NULL,
    id_departamento INTEGER NOT NULL,
    id_fuente_dato INTEGER,
    CONSTRAINT pk_exhumacion PRIMARY KEY (id),
    CONSTRAINT fk_exhumacion_fecha FOREIGN KEY (id_fecha) REFERENCES fecha (id),
    CONSTRAINT fk_exhumacion_departamento FOREIGN KEY (id_departamento) REFERENCES departamento (id),
    CONSTRAINT fk_exhumacion_fuente FOREIGN KEY (id_fuente_dato) REFERENCES fuente_dato (id)
);

CREATE TABLE necropsia (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_persona INTEGER NOT NULL,
    id_fecha_ingreso INTEGER NOT NULL,
    id_municipio INTEGER NOT NULL,
    id_causa_muerte INTEGER,
    id_condicion_edad INTEGER,
    id_fuente_dato INTEGER,
    id_hecho_delictivo INTEGER,
    id_exhumacion INTEGER,
    CONSTRAINT pk_necropsia PRIMARY KEY (id),
    CONSTRAINT fk_necropsia_persona FOREIGN KEY (id_persona) REFERENCES persona (id),
    CONSTRAINT fk_necropsia_fecha FOREIGN KEY (id_fecha_ingreso) REFERENCES fecha (id),
    CONSTRAINT fk_necropsia_municipio FOREIGN KEY (id_municipio) REFERENCES municipio (id),
    CONSTRAINT fk_necropsia_causa FOREIGN KEY (id_causa_muerte) REFERENCES causa_muerte (id),
    CONSTRAINT fk_necropsia_condicion_edad FOREIGN KEY (id_condicion_edad) REFERENCES condicion_edad (id),
    CONSTRAINT fk_necropsia_fuente FOREIGN KEY (id_fuente_dato) REFERENCES fuente_dato (id),
    CONSTRAINT fk_necropsia_hecho FOREIGN KEY (id_hecho_delictivo) REFERENCES hecho_delictivo (id),
    CONSTRAINT fk_necropsia_exhumacion FOREIGN KEY (id_exhumacion) REFERENCES exhumacion (id)
);

CREATE TABLE evaluacion_medica (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_persona INTEGER NOT NULL,
    id_fecha INTEGER NOT NULL,
    id_municipio INTEGER NOT NULL,
    id_clasificacion_evaluacion INTEGER,
    id_orientacion INTEGER,
    id_condicion_edad INTEGER,
    id_grupo_etario INTEGER,
    id_fuente_dato INTEGER,
    id_hecho_delictivo INTEGER,
    CONSTRAINT pk_evaluacion_medica PRIMARY KEY (id),
    CONSTRAINT fk_eval_med_persona FOREIGN KEY (id_persona) REFERENCES persona (id),
    CONSTRAINT fk_eval_med_fecha FOREIGN KEY (id_fecha) REFERENCES fecha (id),
    CONSTRAINT fk_eval_med_municipio FOREIGN KEY (id_municipio) REFERENCES municipio (id),
    CONSTRAINT fk_eval_med_clasificacion FOREIGN KEY (id_clasificacion_evaluacion) REFERENCES clasificacion_evaluacion (id),
    CONSTRAINT fk_eval_med_orientacion FOREIGN KEY (id_orientacion) REFERENCES orientacion (id),
    CONSTRAINT fk_eval_med_condicion_edad FOREIGN KEY (id_condicion_edad) REFERENCES condicion_edad (id),
    CONSTRAINT fk_eval_med_grupo_etario FOREIGN KEY (id_grupo_etario) REFERENCES grupo_etario (id),
    CONSTRAINT fk_eval_med_fuente FOREIGN KEY (id_fuente_dato) REFERENCES fuente_dato (id),
    CONSTRAINT fk_eval_med_hecho FOREIGN KEY (id_hecho_delictivo) REFERENCES hecho_delictivo (id)
);

CREATE TABLE atencion_victima (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_fecha INTEGER NOT NULL,
    id_sede INTEGER NOT NULL,
    id_tipo_delito_atendido INTEGER,
    id_tipo_atencion INTEGER,
    id_persona INTEGER NOT NULL,
    id_municipio_origen INTEGER,
    id_grupo_etario INTEGER,
    id_grupo_etnico INTEGER,
    id_orientacion INTEGER,
    id_fuente_dato INTEGER,
    CONSTRAINT pk_atencion_victima PRIMARY KEY (id),
    CONSTRAINT fk_atencion_victima_fecha FOREIGN KEY (id_fecha) REFERENCES fecha (id),
    CONSTRAINT fk_atencion_victima_sede FOREIGN KEY (id_sede) REFERENCES sede (id),
    CONSTRAINT fk_atencion_victima_tipo_delito FOREIGN KEY (id_tipo_delito_atendido) REFERENCES tipo_delito_atendido (id),
    CONSTRAINT fk_atencion_victima_tipo_atencion FOREIGN KEY (id_tipo_atencion) REFERENCES tipo_atencion (id),
    CONSTRAINT fk_atencion_victima_persona FOREIGN KEY (id_persona) REFERENCES persona (id),
    CONSTRAINT fk_atencion_victima_municipio_origen FOREIGN KEY (id_municipio_origen) REFERENCES municipio (id),
    CONSTRAINT fk_atencion_victima_grupo_etario FOREIGN KEY (id_grupo_etario) REFERENCES grupo_etario (id),
    CONSTRAINT fk_atencion_victima_grupo_etnico FOREIGN KEY (id_grupo_etnico) REFERENCES grupo_etnico (id),
    CONSTRAINT fk_atencion_victima_orientacion FOREIGN KEY (id_orientacion) REFERENCES orientacion (id),
    CONSTRAINT fk_atencion_victima_fuente FOREIGN KEY (id_fuente_dato) REFERENCES fuente_dato (id)
);

CREATE TABLE sentencias_mp_estadistica (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_fecha INTEGER NOT NULL,
    id_tipo_fallo INTEGER NOT NULL,
    cantidad INTEGER NOT NULL,
    CONSTRAINT pk_sentencias_mp_estadistica PRIMARY KEY (id),
    CONSTRAINT fk_sent_mp_fecha FOREIGN KEY (id_fecha) REFERENCES fecha (id),
    CONSTRAINT fk_sent_mp_tipo_fallo FOREIGN KEY (id_tipo_fallo) REFERENCES tipo_fallo (id),
    CONSTRAINT ck_sent_mp_cantidad CHECK (cantidad >= 0)
);

CREATE TABLE sentencias_oj_estadistica (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_departamento INTEGER NOT NULL,
    id_despacho INTEGER NOT NULL,
    id_delito INTEGER NOT NULL,
    id_tipo_fallo INTEGER NOT NULL,
    id_fecha INTEGER NOT NULL,
    cantidad INTEGER NOT NULL,
    CONSTRAINT pk_sentencias_oj_estadistica PRIMARY KEY (id),
    CONSTRAINT fk_sent_oj_departamento FOREIGN KEY (id_departamento) REFERENCES departamento (id),
    CONSTRAINT fk_sent_oj_despacho FOREIGN KEY (id_despacho) REFERENCES despacho_judicial (id),
    CONSTRAINT fk_sent_oj_delito FOREIGN KEY (id_delito) REFERENCES delito (id),
    CONSTRAINT fk_sent_oj_tipo_fallo FOREIGN KEY (id_tipo_fallo) REFERENCES tipo_fallo (id),
    CONSTRAINT fk_sent_oj_fecha FOREIGN KEY (id_fecha) REFERENCES fecha (id),
    CONSTRAINT ck_sent_oj_cantidad CHECK (cantidad >= 0)
);

/* ==========================
   SECTOR INFANTIL
   ========================== */
CREATE TABLE trabajo_infantil (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_persona INTEGER NOT NULL,
    id_area_geografica INTEGER,
    id_fuente_dato INTEGER,
    id_grupo_etario INTEGER,
    id_escolaridad INTEGER,
    asiste_escuela BOOLEAN,
    id_sector_economico INTEGER,
    id_tipo_trabajo INTEGER,
    id_condicion_actividad INTEGER,
    horas_trabajo DECIMAL(9,2),
    ingreso DECIMAL(12,2),
    id_motivo_trabajo INTEGER,
    id_apoyo_hogar INTEGER,
    indicador_domestico BOOLEAN,
    CONSTRAINT pk_trabajo_infantil PRIMARY KEY (id),
    CONSTRAINT fk_trabajo_infantil_persona FOREIGN KEY (id_persona) REFERENCES persona (id),
    CONSTRAINT fk_trabajo_infantil_area FOREIGN KEY (id_area_geografica) REFERENCES area_geografica (id),
    CONSTRAINT fk_trabajo_infantil_fuente FOREIGN KEY (id_fuente_dato) REFERENCES fuente_dato (id),
    CONSTRAINT fk_trabajo_infantil_grupo FOREIGN KEY (id_grupo_etario) REFERENCES grupo_etario (id),
    CONSTRAINT fk_trabajo_infantil_escolaridad FOREIGN KEY (id_escolaridad) REFERENCES escolaridad (id),
    CONSTRAINT fk_trabajo_infantil_sector FOREIGN KEY (id_sector_economico) REFERENCES sector_economico (id),
    CONSTRAINT fk_trabajo_infantil_tipo_trabajo FOREIGN KEY (id_tipo_trabajo) REFERENCES tipo_trabajo (id),
    CONSTRAINT fk_trabajo_infantil_cond_actividad FOREIGN KEY (id_condicion_actividad) REFERENCES condicion_actividad (id),
    CONSTRAINT fk_trabajo_infantil_motivo FOREIGN KEY (id_motivo_trabajo) REFERENCES motivo_trabajo (id),
    CONSTRAINT fk_trabajo_infantil_apoyo FOREIGN KEY (id_apoyo_hogar) REFERENCES apoyo_hogar (id),
    CONSTRAINT ck_trabajo_infantil_horas CHECK (horas_trabajo IS NULL OR horas_trabajo >= 0),
    CONSTRAINT ck_trabajo_infantil_ingreso CHECK (ingreso IS NULL OR ingreso >= 0)
);

/* ==========================
   SALUD
   ========================== */
CREATE TABLE registro_salud (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_tipo_indicador_salud INTEGER NOT NULL,
    id_enfermedad INTEGER,
    id_diagnostico INTEGER,
    id_municipio INTEGER NOT NULL,
    id_fecha INTEGER NOT NULL,
    id_grupo_etario INTEGER,
    id_sexo INTEGER,
    cantidad INTEGER NOT NULL,
    id_fuente_dato INTEGER,
    CONSTRAINT pk_registro_salud PRIMARY KEY (id),
    CONSTRAINT fk_registro_salud_tipo_ind FOREIGN KEY (id_tipo_indicador_salud) REFERENCES tipo_indicador_salud (id),
    CONSTRAINT fk_registro_salud_enfermedad FOREIGN KEY (id_enfermedad) REFERENCES enfermedad (id),
    CONSTRAINT fk_registro_salud_diagnostico FOREIGN KEY (id_diagnostico) REFERENCES diagnostico_cie10 (id),
    CONSTRAINT fk_registro_salud_municipio FOREIGN KEY (id_municipio) REFERENCES municipio (id),
    CONSTRAINT fk_registro_salud_fecha FOREIGN KEY (id_fecha) REFERENCES fecha (id),
    CONSTRAINT fk_registro_salud_grupo_etario FOREIGN KEY (id_grupo_etario) REFERENCES grupo_etario (id),
    CONSTRAINT fk_registro_salud_sexo FOREIGN KEY (id_sexo) REFERENCES sexo (id),
    CONSTRAINT fk_registro_salud_fuente FOREIGN KEY (id_fuente_dato) REFERENCES fuente_dato (id),
    CONSTRAINT ck_registro_salud_cantidad CHECK (cantidad >= 0)
);

COMMIT;
